name: "Close stale issues"
on:
  schedule:
  - cron: "0 * * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: phillipj/close-stale@v4-poc
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        days-before-close: 1
        stale-pr-label: stalled
        stale-issue-label: stalled        
